Milestone 1: Mobile setup, add header and headline
lordksix/portafolio-app pull request #1
Opened 2023-03-22 23:30 UTC by lordksix

# Milestone 1: Mobile setup for project, header, and headline.
In this milestone, the changes are:
- Added GitHub Actions to automate linter.
- Added INDEX.html file with the header and headline
- Added a stylesheet for the HTML file, using the policy "mobile first".  :100: 
- Added .gitignore file to ignore node_modules, among other files.
- Added responsiveness for screens with sizes less than 375px and greater than 375.  :+1:

2023-03-22 23:56 UTC, zieeco requested changes
Hi @lordksix ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 23:56 UTC, zieeco commented on index.html
> +    <div class="menu"></div>
- [ ]  Hey, great adding the hamburger icon, however, this should be in a nav tag to improve the use of the html5 semantic tag. kindly wrap it in the nav tag.

2023-03-22 23:56 UTC, zieeco commented on index.html
> +      <p>My Logo</p>
- Hey, the logo should be in an `a` tag to make it a link so it can be clickable. please, kindly make it a link and not a paragraph.

2023-03-22 23:56 UTC, zieeco commented on index.html
> +    </div>
- Hey, this part of the social media icons is a list of items, and the `ul` is used to group unordered list items on a webpage. Each list item `li` have an anchor `a` tag, wrapping each `img or i` to make the image clickable as the link and to redirect users to the corresponding social media icons added. please, let's improve on this. see below:


 ```
<ul>
    <li><a href=""><img src="" alt=""></a></li> or   <li><a href=""><i class="" ></i></a></li>

</ul>
```

2023-03-22 23:56 UTC, zieeco commented on index.html
> +  <section class="about">
- Hey, the section has a background image as you've not added one yet which makes your design not complete as it's missing the background image. See the Figma design below to compare it with your design:

*The missing background image*
![header-shapes mobile](https://user-images.githubusercontent.com/59397159/227064202-11ace893-922f-407d-8c3a-d278f84bd22b.svg)

*figma design, see the background image*
![Screenshot from 2023-03-23 00-53-25](https://user-images.githubusercontent.com/59397159/227064326-e9008b82-369c-4152-b677-c84a06f450eb.png)

2023-03-23 00:06 UTC, lordksix commented on index.html
> +    <div class="menu"></div>
Great suggestion! Fixed. :1st_place_medal:

2023-03-23 00:07 UTC, lordksix commented on index.html
> +  <section class="about">
There is a broken link caused by a typo . Fixed :+1:

2023-03-23 00:13 UTC, lordksix commented on index.html
> +      <p>My Logo</p>
There was no indication of that in the template but it is a good suggestion

2023-03-23 00:29 UTC, lordksix commented on index.html
> +    </div>
Changed as requested

2023-03-23 00:34 UTC, braincee approved these changes
Hi @lordksix  , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

HIGHLIGHTS

----

- GitHub flow rightfully used ✅
 - Meaningful title and summary for PR ✅
 - Professional README.md file ✅
 - No linter errors ✅


OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-23 00:36 UTC, merged